# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\",\n\rSearchRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"7\n\x0eSearchResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.search.SearchResult\"L\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07tieu_de\x18\x02 \x01(\t\x12\x10\n\x08noi_dung\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x32P\n\rSearchService\x12?\n\x0eSemanticSearch\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=68
  _globals['_SEARCHRESPONSE']._serialized_start=70
  _globals['_SEARCHRESPONSE']._serialized_end=125
  _globals['_SEARCHRESULT']._serialized_start=127
  _globals['_SEARCHRESULT']._serialized_end=203
  _globals['_SEARCHSERVICE']._serialized_start=205
  _globals['_SEARCHSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
